Develop
KoTuK2306/calculator_react pull request #1
Opened 2022-02-07 16:25 UTC by KoTuK2306

2022-02-07 17:00 UTC, IliaSolovev requested changes

2022-02-07 17:00 UTC, IliaSolovev commented on src/App.js
> +    <>
зачем фрагмент?

2022-02-07 17:00 UTC, IliaSolovev commented on src/components/Calculator/Calculator.jsx
> +        onClick={(event) => setNumber(event, setStr, setInput, str, input)}
setNumber используется только тут, не за чем его переносить в отдельный файл

2022-02-07 17:00 UTC, IliaSolovev commented on src/components/Calculator/Calculator.jsx
> +        onClick={(event) => setNumber(event, setStr, setInput, str, input)}
и 5 пропсов это много, сгрупируй их логически и передавай 1-3 пропса, но они будут объектами

2022-02-07 17:00 UTC, IliaSolovev commented on src/components/Calculator/Calculator.jsx
> +        onClick={(event) => setNumber(event, setStr, setInput, str, input)}
https://learn.javascript.ru/object

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/changeSign.js
> +    str = "";
странная логика, у тебя строка равна 0, а ты делаешь ее пустой

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/changeSign.js
> +export const changeSign = (str) => {
str плохое название аргумента

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/changeTextSize.js
> +export const changeTextSize = (str) => {
str плохое название аргумента

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/countUp.js
> +  if (result === "" && subResult !== "") {
subResult это подрезультат, а что это такое не понятно

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/countUp.js
> +    answer = eval(subResult.slice(0, -1));
подумай, как поправить эту ошибку по другому или пиши комментарий

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/countUp.js
> +export const countUp = (result, subResult) => {
плохие названия, потому что ты получаешь результат, результат чего?

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/countUp.js
> +export const countUp = (result, subResult) => {
я бы ожидал результат как вычисленияя чего то внутри функции

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/countUp.js
> +  if (result === "" && subResult !== "") {
можешь сразу возвращать значение внутри if

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/numberProtection.js
> +export const numberProtection = (number, countUpIsClicked, event) => {
от чего защищаем числа?

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/numberProtection.js
> +export const numberProtection = (number, countUpIsClicked, event) => {
нахуя тут нужен event

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/numberProtection.js
> +    number = event.target.innerHTML;
в реакте ты манипулируешь dom`ом напрямую, выглядит как хуита

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/numberProtection.js
> +    number = event.target.innerHTML;
передай сюда уже то, что лежит в html, но без обращения к нему

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/operationProtection.js
> +export const operationProtection = (num, sign) => {
добавь проверку этого прям в самой функции, которая обрабатывает клие на кнопку, и создай функцию, которая будет жрать любой знак и делать магию

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/point.js
> +  let point = str;
почему у тебя тогда аргумент str

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/point.js
> +  if (point.includes(".")) return point;
у тебя переменная называется точка и ты проверяешь есть ли в ней точка?

2022-02-07 17:00 UTC, IliaSolovev commented on src/functions/setNumber.js
> +export const setNumber = (event, setStr, setInput, str, input) => {
создай под каждую кнопку свой обработчик и удали нахуй этот ужасный свич кейс

2022-02-07 17:00 UTC, IliaSolovev commented
отключи в настройках eslint eval

2022-02-09 20:56 UTC, KoTuK2306 commented on src/App.js
> +import Calculator from "./components/Calculator/Calculator";
лучше использовать именованный экспорт

2022-02-09 20:56 UTC, KoTuK2306 commented on src/components/Calculator/Button/Button.jsx
> +export default Button;
лучше использовать именованный экспорт

2022-02-09 20:56 UTC, KoTuK2306 commented on src/components/Calculator/Calculator.jsx
> +import classes from "./calculator.module.css";
лучше импортировать стили внизу

2022-02-09 20:56 UTC, KoTuK2306 commented on src/components/Calculator/OperationButton/OperationButton.jsx
> +const OperationButton = (props) => {
используй уже созданный компонент и давай доп стили через пропсы

2022-02-09 20:56 UTC, KoTuK2306 commented on src/functions/calcPercent.js
> +  if (sign === "+" || sign === "-") {
```
["+", "-"].includes(sign)
```

2022-02-09 20:56 UTC, KoTuK2306 commented on src/functions/calcPercent.js
> +  if (sign === "*" || sign === "/") {
как выше

2022-02-09 20:56 UTC, KoTuK2306 commented on src/functions/calcPercent.js
> +    values.setStr(eval(equation + sign + equation * (values.str / 100))); //Подсчёт процента от числа
создать переменную и написать коммент

2022-02-09 20:56 UTC, KoTuK2306 commented on src/functions/changeTextSize.js
> +  if (inputedNumber.length > 15 && inputedNumber.length <= 38) {
```suggestion
  if (inputedNumber.length > 15 && inputedNumber.length < 39) {
```

2022-02-09 20:56 UTC, KoTuK2306 commented on src/functions/changeTextSize.js
> +  } else resultWindow.style = "font-size: 35px";
используй пустой return

2022-02-09 20:56 UTC, KoTuK2306 commented on src/functions/changeTextSize.js
> +  } else resultWindow.style = "font-size: 35px";
используй переменную для размера

2022-02-09 20:56 UTC, KoTuK2306 commented on src/functions/clean.js
> +  resultWindow.style = "font-size: 35px"; //Сбросить стили окна результата
юзай переменную выше тут

2022-02-09 20:56 UTC, KoTuK2306 commented on src/functions/countUp.js
> +  } else {
пустой return

2022-02-09 20:56 UTC, KoTuK2306 commented on src/functions/protectionFromDoubleSigns.js
> +export const protectionFromDoubleSigns = (inputedOperations, inputedNumber, sign) => {
подумать над более хорошим названием

2022-02-09 20:56 UTC, KoTuK2306 commented on src/functions/protectionFromDoubleSigns.js
> +  } else return inputedOperations + inputedNumber + sign;
ненужный else

2022-02-09 20:56 UTC, KoTuK2306 commented on src/functions/setNumber.js
> +  } else values.setStr(values.str + number);
пустой return

2022-02-09 20:56 UTC, KoTuK2306 commented on src/index.js
> +import "./index.css";
вниз перенеси стили

2022-02-10 11:56 UTC, IliaSolovev commented on src/functions/calcPercent.js
> +  if (sign === "+" || sign === "-") {
Зачем придумывать такой механизм, когда только два возможных случая?

2022-02-10 11:57 UTC, IliaSolovev commented on src/functions/calcPercent.js
> +    values.setStr(eval(equation + sign + equation * (values.str / 100))); //Подсчёт процента от числа
если эта переменная будет только передаваться в eval, то зачем ее создавать, если уже есть комментарий. 
Можно было бы создать переменную без комментария, если ее название было понятным. Но так как все равно остается комментарий, то зачем это нужно

2022-02-10 11:58 UTC, IliaSolovev commented on src/functions/changeTextSize.js
> +  if (inputedNumber.length > 15 && inputedNumber.length <= 38) {
создай для чисел 15 и 39 константы прям в этом файле. И понятно  название дай. Сейчас это какие то магические числа. Тип почему имено 15 и 39

2022-02-10 12:00 UTC, IliaSolovev commented on src/functions/changeTextSize.js
> +  } else resultWindow.style = "font-size: 35px";
так как на основе этой переменной ничего не будет расчитываться, то внутри этой функции нет смысла создавать перемененную под размеры

2022-02-10 12:01 UTC, IliaSolovev commented on src/functions/protectionFromDoubleSigns.js
> +export const protectionFromDoubleSigns = (inputedOperations, inputedNumber, sign) => {
меня устроило название, потому что я понял для чего эта функция

2022-02-10 12:01 UTC, IliaSolovev commented on src/functions/protectionFromDoubleSigns.js
> +export const protectionFromDoubleSigns = (inputedOperations, inputedNumber, sign) => {
возможно pretection нужно на что то заменить

2022-02-10 12:05 UTC, IliaSolovev requested changes

2022-02-10 12:05 UTC, IliaSolovev commented on src/index.js
> +import "./index.css";
а для чего? просто религиозное убеждение?)

2022-02-10 12:05 UTC, IliaSolovev commented on src/functions/sqrt.js
> +  return Number(Math.sqrt(str).toFixed(7));
здесь не только вычисление корня

2022-02-10 12:05 UTC, IliaSolovev commented on src/functions/setOperationWithNumber.js
> +  if (isNaN(Number(values.input.slice(-1))) && values.str === "") {
раздели эту операцию на несколько маленьких и под каждую создай переменную

2022-02-10 12:05 UTC, IliaSolovev commented on src/functions/setNumber.js
> +  changeTextSize(values.str, resultWindow);
ты получаешь тут старую строку

2022-02-12 14:31 UTC, IliaSolovev requested changes

2022-02-12 14:31 UTC, IliaSolovev commented on src/components/Calculator/Calculator.jsx
> +import { setOperationWithNumber } from "../../functions/setOperationWithNumber";
я уже рассказывал, что такое реэкспорты, вспоминай

2022-02-12 14:31 UTC, IliaSolovev commented on src/functions/point.js
> +  if (inputedNumber.length === 0) return setStr("0."); //Если была нажата точка, а число отсутствует,
ты говоришь, что число отсутствует, было бы хорошо знать, где это число отсутствует
и название переменной утверждает, что это число, как оно может отсутствовать

2022-02-12 14:48 UTC, IliaSolovev requested changes

2022-02-12 14:48 UTC, IliaSolovev commented on src/functions/sqrtRounded.js
> +export const sqrtRounded = (str) => {
берем корень из строки? ват?

2022-02-12 14:48 UTC, IliaSolovev commented on src/functions/setOperationWithNumber.js
> +  const lastOperation = values.input.slice(-1); //Выборка последнего знака операции
??????

2022-02-12 14:48 UTC, IliaSolovev commented on src/functions/changeTextSize.js
> +  if (inputedNumber.length > 17 && inputedNumber.length < 44) {
магические числа, вокруг которых ты танцуешь, дай им названия

2022-02-12 14:48 UTC, IliaSolovev commented on src/functions/changeTextSize.js
>      resultWindow.style = `font-size: ${size.smallTextSize}px`;
не мутируем, это плохо

2022-02-12 15:08 UTC, IliaSolovev requested changes

2022-02-12 15:08 UTC, IliaSolovev commented on src/components/Calculator/Calculator.jsx
> +  const [str, setStr] = useState("");
ебучий случай, да переименуй ты ее уже

2022-02-12 15:08 UTC, IliaSolovev commented on src/components/Calculator/Calculator.jsx
> +          onClick={(event) => setOperationWithNumber(values, event.target.innerHTML)}
ну ведь это одна и та же функция, ну создай ты ее один раз и просто сюда передай. еще почитай про useCallback

2022-02-12 15:08 UTC, IliaSolovev commented on src/functions/clean.js
> +export const clean = (setStr, setInput, resultWindow) => {
clear

2022-02-12 15:08 UTC, IliaSolovev commented on src/functions/countUp.js
> +    values.setStr(Number(eval(values.input.slice(0, -1))));
создай для slice переменную

2022-02-12 15:08 UTC, IliaSolovev commented on src/functions/setNumber.js
> +    //Если число после подсёта имеет тип данных number, то оно стирается при наборе следующих цифр
откуда стриается

2022-02-13 10:11 UTC, KoTuK2306 commented on src/index.js
> +import "./index.css";
Я поддерживаю такое религиозное убеждение

2022-02-13 13:47 UTC, IliaSolovev requested changes

2022-02-13 13:47 UTC, IliaSolovev commented on src/components/Calculator/Calculator.jsx
>    const values = {
почему в значениях лежит что то , что начинается с Set? переменная называется значения

2022-02-13 13:47 UTC, IliaSolovev commented on src/components/Calculator/Calculator.jsx
> +  const [windowWithNums, setWindowWithNums] = useState("");
переменная ссылается на окно?

2022-02-13 13:47 UTC, IliaSolovev commented on src/components/Calculator/Calculator.jsx
> +  const setNumberCallback = useCallback((event) => {
в чем смысл usecallback без зависимостей

2022-02-13 13:47 UTC, IliaSolovev commented on src/functions/changeTextSize.js
> +const numberLenght = 17;
1 не правильно написал слова длина
2 почему бы не создать нормальное название переменной, без комментария, я верю, что ты сможешь

2022-02-13 13:47 UTC, IliaSolovev commented on src/functions/clear.js
> +  setNum(""); //Очистить окно набора чисел
абсолютно не ненужные комментарии, подумай сам почему

2022-02-13 13:47 UTC, IliaSolovev commented on src/functions/setOperationWithNumber.js
> +    //values.num - окно с вводом цифр
values.num - окно с вводом цифр, но рядом есть переменная в которой фигурирует слово окно

2022-02-13 13:48 UTC, IliaSolovev commented on src/components/Calculator/Calculator.jsx
> +  const values = memo(
memo != хук

2022-02-13 13:48 UTC, IliaSolovev commented on src/components/Calculator/Calculator.jsx
> +    [values, resultWindow]
лайк, ты смог причитать апи

2022-02-21 08:01 UTC, closed without merging